force-app/main/default/objects/Budget_Period__c/Budget_Period__c.object-meta.xml
<CustomObject>
    <description>A designated period of budgeting</description>
    <label>Budget Period</label>
    <nameField>
        <label>Budget Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Period__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Additional information about the budget period</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Budget_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The closing date of the budget period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Budget_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The beginning date of the budget period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Budget_Period__c/fields/Total_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense__c</fullName>
    <description>The total expenses during the budget period</description>
    <label>Total Expense</label>
    <summarizedField>Transaction_Item__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>Debit</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction_Item__c.Budget_Period__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget_Period__c/fields/Total_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Income__c</fullName>
    <description>The total income during the budget period</description>
    <label>Total Income</label>
    <summarizedField>Transaction_Item__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>Credit</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction_Item__c.Budget_Period__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/BudgetPeriodController.cls
public with sharing class BudgetPeriodController {

    static Integer PAGE_SIZE = 9;

    @AuraEnabled(Cacheable=true)
    public static PagedResult getBudgetPeriods(Integer pageNumber) {
        Integer pageSize = BudgetPeriodController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize;

        PagedResult result = new PagedResult();

        result.pageSize = pageSize;
        result.pageNumber = pageNumber;
        result.totalItemCount = Database.countQuery('SELECT count() FROM Budget_Period__c');
        result.records = Database.query('SELECT Id, Name, Description__c, Start_Date__c, End_Date__c, Total_Income__c, Total_Expense__c, Total_Saving__c FROM Budget_Period__c  ORDER BY Name LIMIT :pageSize OFFSET :offset');
        
        return result;
    }
}