force-app/main/default/objects/Budget_Period__c/Budget_Period__c.object-meta.xml
<CustomObject>
    <description>A designated period of budgeting</description>
    <label>Budget Period</label>
    <nameField>
        <label>Budget Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The closing date of the budget period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Budget_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The beginning date of the budget period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BudgetPeriodControllerTest.cls
@isTest
private class BudgetPeriodControllerTest {
    
    @TestSetup
    static void setup() {
        List<Budget_Period__c> budgetPeriods = new List<Budget_Period__c>{
            new Budget_Period__c(
                Name = 'January 2019',
                Start_Date__c = Date.newInstance(2019, 1, 1),
                End_Date__c = Date.newInstance(2019, 1, 31)
            ),
            new Budget_Period__c(
                Name = 'February 2019',
                Start_Date__c = Date.newInstance(2019, 2, 1),
                End_Date__c = Date.newInstance(2019, 2, 28)
            ),
            new Budget_Period__c(
                Name = 'March 2019',
                Start_Date__c = Date.newInstance(2019, 3, 1),
                End_Date__c = Date.newInstance(2019, 3, 31)
            )
        };

        insert budgetPeriods;
    }

    @isTest
    static void testGetBudgetPeriods() {

        Test.startTest();
        PagedResult result = BudgetPeriodController.getBudgetPeriods(1);
        Test.stopTest();

        System.assertEquals(3, result.totalItemCount);
        System.assertEquals(3, result.records.size());
    }
}