force-app/main/default/objects/Budget_Period__c/Budget_Period__c.object-meta.xml
<CustomObject>
    <description>A designated period of budgeting</description>
    <label>Budget Period</label>
    <nameField>
        <label>Budget Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The closing date of the budget period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Budget_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The beginning date of the budget period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Item__c/Transaction_Item__c.object-meta.xml
<CustomObject>
    <description>A transaction belonging to a budget period</description>
    <label>Transaction Item</label>
    <nameField>
        <label>Transaction Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of the transaction</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Item__c/fields/Budget_Period__c.field-meta.xml
<CustomField>
    <fullName>Budget_Period__c</fullName>
    <description>The budget period this transaction belongs to</description>
    <label>Budget Period</label>
    <referenceTo>Budget_Period__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date of the transaction</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the transaction</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionItemControllerTest.cls
@isTest
private class TransactionItemControllerTest {
    
    @TestSetup
    static void setup() {
        Budget_Period__c budgetPeriod = new Budget_Period__c(
            Name = 'January 2019',
            Start_Date__c = Date.newInstance(2019, 1, 1),
            End_Date__c = Date.newInstance(2019, 1, 31)
        );

        insert budgetPeriod;

        List<Transaction_Item__c> transactionItems = new List<Transaction_Item__c>{
            new Transaction_Item__c(
                Budget_Period__c = budgetPeriod.Id,
                Name = 'Job paycheck',
                Amount__c = 1000.0,
                Type__c = 'Credit',
                Date__c = Date.newInstance(2019, 1, 15)
            ),
            new Transaction_Item__c(
                Budget_Period__c = budgetPeriod.Id,
                Name = 'Mortgage payment',
                Amount__c = 900.0,
                Type__c = 'Debit',
                Date__c = Date.newInstance(2019, 1, 20)
            )
        };

        insert transactionItems;
    }

    static Budget_Period__c getBudgetPeriod() {
        return [
            SELECT 
                Id 
            FROM 
                Budget_Period__c
            LIMIT 1
        ];
    }

    @isTest
    static void testGetTransactionItems() {
        Budget_Period__c budgetPeriod = getBudgetPeriod();

        Test.startTest();
        Transaction_Item__c[] transactionItems = TransactionItemController.getTransactionItems(budgetPeriod.Id);
        Test.stopTest();

        System.assertEquals(2, transactionItems.size());
    }
}