force-app/main/default/objects/Budget_Period__c/Budget_Period__c.object-meta.xml
<CustomObject>
    <description>A designated period of budgeting</description>
    <label>Budget Period</label>
    <nameField>
        <label>Budget Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Item__c/Transaction_Item__c.object-meta.xml
<CustomObject>
    <description>A transaction belonging to a budget period</description>
    <label>Transaction Item</label>
    <nameField>
        <label>Transaction Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of the transaction</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Item__c/fields/Budget_Period__c.field-meta.xml
<CustomField>
    <fullName>Budget_Period__c</fullName>
    <description>The budget period this transaction belongs to</description>
    <label>Budget Period</label>
    <referenceTo>Budget_Period__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date of the transaction</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the transaction</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionItemController.cls
public with sharing class TransactionItemController {

    @AuraEnabled
    public static List<Transaction_Item__c> getTransactionItems(String budgetPeriodId) {
        List<Transaction_Item__c> items = [
            SELECT 
                Id,
                Name, 
                Amount__c,
                Date__c,
                Type__c
            FROM 
                Transaction_Item__c 
            WHERE 
                Budget_Period__c = :budgetPeriodId
            ORDER BY Date__c
        ];
        
        return items;
    }

    @AuraEnabled
    public static void deleteTransactionItem(String transactionItemId) {
        if (String.isNotBlank(transactionItemId)) {
            try {
                delete [SELECT Id FROM Transaction_Item__c WHERE Id = :transactionItemId];
            } catch (Exception e) {
                throw new AuraException(e.getMessage());
            }
        }
    }
}